name = "memorize-words"
pages_build_output_dir = "build"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "memorize-db"
database_id = "43a46993-5011-4711-b48d-4ce412be8575"
